### ISSUE TITLE
Please, add the CoinEx Smart Chain to the family

### ISSUE THREAD

**Issue by kitobelix** [arddluma/awesome-list-rpc-nodes-providers#16]
Hello! Please, if you can, add the new Coinex Smart Chain to the family (CSC). Let me provide some information about it to easen the process.

https://docs.coinex.org/#/en-us/introduction

Docs on how to deploy a Node: https://docs.coinex.org/#/en-us/node_compile
Docs on how to deploy and run a validator node: https://docs.coinex.org/#/en-us/validator_intro

Chain ID: 
Mainnet: 52
Testnet: 53

Mainnet RPC endpoints:
https://rpc.coinex.net/
https://rpc1.coinex.net/
https://rpc2.coinex.net/
https://rpc3.coinex.net/
https://rpc4.coinex.net/

Mainnet WSS endpoints:
wss://csc-ws.coinex.net/

Explorer:
https://www.coinex.net/

Testnet information: https://docs.coinex.org/#/en-us/testnet

Testnet Faucet: https://testnet.coinex.net/faucet

Thank you for mantaining this!

**Comment by arddluma** [comment]
Hi there,
Feel free to fork the repo and create a PR :)
Also, could you please list projects deployed on this chain? Why should we add CoinEx to the list?!
ty

**Comment by arddluma** [comment]
Hey @kitobelix , any update on this?

**Comment by kitobelix** [comment]
Hey, sorry! I've been short of time. 

they launched about a year ago, and they're just beginning to publish theirselves to allow others to come. I've been speaking with the team recently, they look good and there is a huge opportunity of taking it from the beginning. There's also the possibility of competing against the BSC with the decentralization factor that they have.

It's hard to build a blockchain and look for users and projects to come. I'm just giving a hand. My project is going to be there too.
