### ISSUE TITLE
machine-readable list is available

### ISSUE THREAD

**Issue by svanas** [arddluma/awesome-list-rpc-nodes-providers#25]
Thank you for [awesome-list-rpc-nodes-providers](https://github.com/arddluma/awesome-list-rpc-nodes-providers). I have created this [machine-readable list](https://github.com/svanas/ethereum-node-list). Can you link to the list maybe?

**Comment by arddluma** [comment]
wow! this is pretty cool, thanks for the shoutout! For sure, will add this to the list!
